export const MODELS_PRICING = [
  {
    providerType: "openai",
    modelId: "gpt-4o",
    displayName: "GPT-4o",
    inputCostPer1mTokens: "2.50",
    outputCostPer1mTokens: "10.00",
    maxContextWindow: 128000,
    supportsVision: true,
    supportsTools: true,
    category: "flagship" as const,
  },
  {
    providerType: "openai",
    modelId: "gpt-4o-mini",
    displayName: "GPT-4o Mini",
    inputCostPer1mTokens: "0.15",
    outputCostPer1mTokens: "0.60",
    maxContextWindow: 128000,
    supportsVision: true,
    supportsTools: true,
    category: "fast" as const,
  },
  {
    providerType: "openai",
    modelId: "gpt-4-turbo",
    displayName: "GPT-4 Turbo",
    inputCostPer1mTokens: "10.00",
    outputCostPer1mTokens: "30.00",
    maxContextWindow: 128000,
    supportsVision: true,
    supportsTools: true,
    category: "flagship" as const,
  },
  {
    providerType: "openai",
    modelId: "o3-mini",
    displayName: "o3 Mini",
    inputCostPer1mTokens: "1.10",
    outputCostPer1mTokens: "4.40",
    maxContextWindow: 200000,
    supportsVision: false,
    supportsTools: true,
    category: "balanced" as const,
  },
  {
    providerType: "anthropic",
    modelId: "claude-sonnet-4-20250514",
    displayName: "Claude Sonnet 4",
    inputCostPer1mTokens: "3.00",
    outputCostPer1mTokens: "15.00",
    maxContextWindow: 200000,
    supportsVision: true,
    supportsTools: true,
    category: "flagship" as const,
  },
  {
    providerType: "anthropic",
    modelId: "claude-haiku-4-5-20251001",
    displayName: "Claude Haiku 4.5",
    inputCostPer1mTokens: "0.80",
    outputCostPer1mTokens: "4.00",
    maxContextWindow: 200000,
    supportsVision: true,
    supportsTools: true,
    category: "fast" as const,
  },
  {
    providerType: "anthropic",
    modelId: "claude-opus-4-6",
    displayName: "Claude Opus 4.6",
    inputCostPer1mTokens: "15.00",
    outputCostPer1mTokens: "75.00",
    maxContextWindow: 200000,
    supportsVision: true,
    supportsTools: true,
    category: "flagship" as const,
  },
  {
    providerType: "google",
    modelId: "gemini-2.0-flash",
    displayName: "Gemini 2.0 Flash",
    inputCostPer1mTokens: "0.10",
    outputCostPer1mTokens: "0.40",
    maxContextWindow: 1000000,
    supportsVision: true,
    supportsTools: true,
    category: "fast" as const,
  },
  {
    providerType: "google",
    modelId: "gemini-2.5-pro",
    displayName: "Gemini 2.5 Pro",
    inputCostPer1mTokens: "1.25",
    outputCostPer1mTokens: "10.00",
    maxContextWindow: 1000000,
    supportsVision: true,
    supportsTools: true,
    category: "flagship" as const,
  },
];
